# Generated by Django 5.0.6 on 2024-07-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='username'),
        ),
    ]
